export const projectsData = [
  {
    title: 'DevFlow',
    desc: 'A forum for programmers where you can ask questions on a wide range of topics, engage in discussions, and share your knowledge and expertise.',
    type: 'web-application',
    categories: [1],
    icons: [
      { icon: 'cibNextJs', fill: 'fill-slate-200' },
      { icon: 'cibTypescript', fill: 'fill-blue-400' },
    ],
    technologyIds: [2, 4, 5],
    imageUrl: [
      'https://onzxuggvoclteqxynecc.supabase.co/storage/v1/object/sign/projects/DevFlow/1.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9qZWN0cy9EZXZGbG93LzEucG5nIiwiaWF0IjoxNzI1OTc1NTk5LCJleHAiOjE3NTc1MTE1OTl9.W9Weji1BVJkvyzGlvhArAunlIsWxN3ao3fJd77S7kR8&t=2024-09-10T13%3A39%3A58.623Z',
      'https://onzxuggvoclteqxynecc.supabase.co/storage/v1/object/sign/projects/DevFlow/2.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9qZWN0cy9EZXZGbG93LzIucG5nIiwiaWF0IjoxNzI1OTc1NjA3LCJleHAiOjE3NTc1MTE2MDd9.KI8SW_AGP3WeajRUEzNUUJORlspIetU0Be3AMhJ9oqU&t=2024-09-10T13%3A40%3A07.061Z',
      'https://onzxuggvoclteqxynecc.supabase.co/storage/v1/object/sign/projects/DevFlow/Screenshot_1.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9qZWN0cy9EZXZGbG93L1NjcmVlbnNob3RfMS5wbmciLCJpYXQiOjE3MjU5NzU2MTksImV4cCI6MTc1NzUxMTYxOX0.C4gS79z3v4sqKICXXR5q8rvR0YNF1u65qHjKCT11_NQ&t=2024-09-10T13%3A40%3A19.100Z',
      'https://onzxuggvoclteqxynecc.supabase.co/storage/v1/object/sign/projects/DevFlow/Screenshot_2.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9qZWN0cy9EZXZGbG93L1NjcmVlbnNob3RfMi5wbmciLCJpYXQiOjE3MjU5NzU2MjksImV4cCI6MTc1NzUxMTYyOX0.BgAk_VcYPJ7WSPBjl2A_Q071egjDZIwcHQOjpBZkhIk&t=2024-09-10T13%3A40%3A29.170Z',
    ],
  },
  {
    title: 'Inventory',
    desc: 'A comprehensive CRM system for an electronics store, designed to efficiently manage orders, products, and customer interactions.',
    type: 'web-application',
    categories: [1, 2],
    icons: [
      { icon: 'cibReact', fill: 'fill-blue-500' },
      { icon: 'cibNodeJs', fill: 'fill-green-500' },
      { icon: 'cibMongodb', fill: 'fill-lime-600' },
    ],
    technologyIds: [1, 5, 9],
  },
  {
    title: 'Weather Wise',
    desc: 'A weather forecast app with automatic location detection, charts, autocomplete features, and various additional functionalities.',
    type: 'web-application',
    categories: [1],
    icons: [{ icon: 'cibVueJs', fill: 'fill-green-500' }],
    technologyIds: [4],
  },
  {
    title: 'Next Pizza',
    desc: 'An online platform for ordering pizzas with a customizable menu, fast delivery, and various payment options.',
    type: 'web-application',
    categories: [1, 2],
    icons: [{ icon: 'cibVueJs', fill: 'fill-green-500' }],
    technologyIds: [4],
  },
  {
    title: 'Game Arcade',
    desc: 'A web-based arcade gaming platform offering a wide range of games and leaderboards to compete with friends.',
    type: 'web-application',
    categories: [4],
    icons: [{ icon: 'cibVueJs', fill: 'fill-green-500' }],
    technologyIds: [4],
  },
  {
    title: 'Simple Portfolio',
    desc: 'A personal portfolio website to showcase projects, skills, and contact information.',
    type: 'web-application',
    categories: [1],
    icons: [{ icon: 'cibReact', fill: 'fill-blue-500' }],
    technologyIds: [2],
  },
  {
    title: 'Social Network',
    desc: 'A social networking platform for connecting with friends, sharing updates, and joining communities.',
    type: 'web-application',
    categories: [4],
    icons: [{ icon: 'cibVueJs', fill: 'fill-green-500' }],
    technologyIds: [4],
  },
  {
    title: 'E-commerce Platform',
    desc: 'An advanced e-commerce platform with features such as product listings, shopping cart, checkout, and user reviews.',
    type: 'web-application',
    categories: [1, 3],
    icons: [
      { icon: 'cibNextJs', fill: 'fill-black' },
      { icon: 'cibStripe', fill: 'fill-blue-500' },
    ],
    technologyIds: [3],
  },
  {
    title: 'Fitness Tracker',
    desc: 'A mobile-friendly web app to track workouts, monitor progress, and set fitness goals.',
    type: 'web-application',
    categories: [2],
    icons: [
      { icon: 'cibReact', fill: 'fill-blue-500' },
      { icon: 'cibNodeJs', fill: 'fill-green-500' },
    ],
    technologyIds: [2, 6],
  },
  {
    title: 'Blog Platform',
    desc: 'A blogging platform where users can create, edit, and share posts, with features for comments and social sharing.',
    type: 'web-application',
    categories: [1],
    icons: [
      { icon: 'cibReact', fill: 'fill-blue-500' },
      { icon: 'cibTailwindCss', fill: 'fill-blue-500' },
    ],
    technologyIds: [2],
  },
];
